"""
Test cases for tensorflow.python.ops.check_ops module.
Generated by TestAgent.
"""
import math
import pytest
import numpy as np
from unittest.mock import Mock, patch, MagicMock
import tensorflow as tf
from tensorflow.python.ops import check_ops

# START:HEADER
# END:HEADER

# START:CASE_01
# END:CASE_01

# START:CASE_02
# END:CASE_02

# START:CASE_03
# END:CASE_03

# START:CASE_04
# END:CASE_04

# START:CASE_05
# END:CASE_05

# START:FOOTER
# END:FOOTER